id: 0c75cbf5-cadb-4c89-a860-e7687c9b4c3e
type: application
interactions:
- targetId: 3ca94e3c-5205-4ee6-bdd7-d5f26737eda7
  type: service
  level: component
- targetId: 9407576b-6e9f-46d5-8ddf-67e7061c955a
  type: domain
  level: component
annotations:
- namespace: c4modeler
  name: position
  value:
    fdd7938c-ec2f-4a9b-b414-f9f14249bd88:
      x: 140
      y: 124.5
name: NewApplication
description: Description for NewApplication
baseApiUrl: ca/baseapi
